### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by KaMyKaSii** [j2rong/HeadsOff#1]
当应用程序将支持其他语言？因为不是每个人都讲中国话，至少有英文帮助

**Comment by j2rong** [comment]
There is a built-in English translation, it will be displayed if system language is set to English.

**Comment by j2rong** [comment]
Set English as default language

**Comment by j2rong** [comment]
There is a built-in English translation, it will be displayed if system language is set to English.

**Comment by amokkatgithub** [comment]
Make english by default if system language is not chinese. Or make a switch.

**Comment by KaMyKaSii** [comment]
Also think English should be the default language. And if in the near future provide multi languages, tell me to make the portuguese brazilian translation

**Comment by j2rong** [comment]
@KaMyKaSii 
Thank you, for how to make translation please see [here](https://github.com/j2rong/HeadsOff#contributing)

**Comment by j2rong** [comment]
about this issue, check out the latest release (v0.5.78)
