### ISSUE TITLE
Blocking heads-up notifications of almost all apps is unpractical

### ISSUE THREAD

**Issue by Aironfaar** [j2rong/HeadsOff#3]
I use this Xposed module to block all heads-up notifications except for the Dialer's. On my OS, as long as the Dialer's heads-up is set to be displayed, the Dialer won't come to the foreground; that way, being called doesn't immediately interrupt whatever I'm currently doing, but I couldn't care less for any of the other heads-up notifications.

Right now, that means I have all apps toggled to be filtered except for the Dialer. Whenever I install a new app, I have to toggle the filter on in HeadsOff. I also imagine that this huge list of filtered apps causes a lot of “Is this notification filtered?“ ifs, which gets less and less pretty the more apps I install.

That said, I'd love to see a toggle in the settings that allows for reverse filtering as in “while reverse filtering is enabled, only show notifications from apps toggled on with per-app RegEx blacklists for those apps“. This way, my use-case would be covered completely with what seems to be comparably easy modifications. Until then, I'll keep using this awesome module the way I am right now.

Cheers!

**Comment by j2rong** [comment]
First of all, only heads-up notifications get to be checked, Android itself has several restrictions on heads-ups, so unless you get a lot of heads-ups, it should be in a reasonable cost.

And whether "reverse" or not, each heads-up notifications still needs to be checked to see if it's posted by the selected app(s).

**Comment by Aironfaar** [comment]
I currently have around 200 apps installed, including system apps. Whether the module goes through a list of 199 to check whether

**Comment by Aironfaar** [comment]
I currently have around 200 apps installed, including system apps. Whether the module goes through a list of 199 to check whether a heads-up notification is from one of them and thus to be blocked or checks for just one to see whether it should be let through probably won't make any perceivable difference in performance, that's true; the optimization approach would be more of a thing for perfectionists.

That said, this is a request for a quality of life feature. After all, while it wouldn't do much to improve performance, it does make a big difference to the user whether he has to toggle 199 apps to be blocked plus one for each app that will be installed later or to toggle one switch in the settings and one for the app he wants heads-up notifications to be allowed for.

Either way, your module works great and I'm happy that I found it. Thanks for creating it.

EDIT: Sorry for the many posts. My browser didn't react to clicking the comment button, but actually did post the comments each time I tried...

**Comment by Aironfaar** [comment]
I currently have around 200 apps installed, including system apps. Whether the module goes through a list of 199 to check whether a heads-up notification is from one of them and thus to be blocked or checks for just one to see whether it should be let through probably won't make any perceivable difference in performance, that's true; the optimization approach would be more of a thing for perfectionists.

That said, this is a request for a quality of life feature. After all, while it wouldn't do much to improve performance, it does make a big difference to the user whether he has to toggle 199 apps to be blocked plus one for each app that will be installed later or to toggle one switch in the settings and one for the app he wants heads-up notifications to be allowed for.

Either way, your module works great and I'm happy that I found it. Thanks for creating it.

**Comment by Aironfaar** [comment]
I currently have around 200 apps installed, including system apps. Whether the module goes through a list of 199 to check whether a heads-up notification is from one of them and thus to be blocked or checks for just one to see whether it should be let through probably won't make any perceivable difference in performance, that's true; the optimization approach would be more of a thing for perfectionists.

That said, this is a request for a quality of life feature. After all, while it wouldn't do much to improve performance, it does make a big difference to the user whether he has to toggle 199 apps to be blocked plus one for each app that will be installed later or to toggle one switch in the settings and one for the app he wants heads-up notifications to be allowed for.

Either way, your module works great and I'm happy that I found it. Thanks for creating it.

**Comment by Aironfaar** [comment]
I currently have around 200 apps installed, including system apps. Whether the module goes through a list of 199 to check whether a heads-up notification is from one of them and thus to be blocked or checks for just one to see whether it should be let through probably won't make any perceivable difference in performance, that's true; the optimization approach would be more of a thing for perfectionists.

That said, this is a request for a quality of life feature. After all, while it wouldn't do much to improve performance, it does make a big difference to the user whether he has to toggle 199 apps to be blocked plus one for each app that will be installed later or to toggle one switch in the settings and one for the app he wants heads-up notifications to be allowed for.

Either way, your module works great and I'm happy that I found it. Thanks for creating it.

**Comment by j2rong** [comment]
I think what you need is:
a toggle for all apps
auto check when new app installed
